language: node_js
node_js:
  - "4.1"
  - "4.0"
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
  - '[[ "${TRAVIS_NODE_VERSION}" != "4.1" || "${TRAVIS_BRANCH}" != "master" ]] || npm run deploy-docs'
